// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-Dd4h8aQwDSYhrg6xwQbPZ0WLgDzP78',
    appId: '1:490682245252:web:33372159680f3af87122d1',
    messagingSenderId: '490682245252',
    projectId: 'fir-flutter-codelab-77a02',
    authDomain: 'fir-flutter-codelab-77a02.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-77a02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9xXIgMQdOTXEyYHlaPVusYrD0maxy1xI',
    appId: '1:490682245252:android:15126b4f6577ea437122d1',
    messagingSenderId: '490682245252',
    projectId: 'fir-flutter-codelab-77a02',
    storageBucket: 'fir-flutter-codelab-77a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsV1yMyR_2sg5YVER8vaAoYNflu8WKCQ',
    appId: '1:490682245252:ios:cfdc4db56d2129277122d1',
    messagingSenderId: '490682245252',
    projectId: 'fir-flutter-codelab-77a02',
    storageBucket: 'fir-flutter-codelab-77a02.appspot.com',
    iosClientId: '490682245252-5n9h1r1u23vr8fmd6jfd4a6u16si4239.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsV1yMyR_2sg5YVER8vaAoYNflu8WKCQ',
    appId: '1:490682245252:ios:cfdc4db56d2129277122d1',
    messagingSenderId: '490682245252',
    projectId: 'fir-flutter-codelab-77a02',
    storageBucket: 'fir-flutter-codelab-77a02.appspot.com',
    iosClientId: '490682245252-5n9h1r1u23vr8fmd6jfd4a6u16si4239.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
